services:
  app:
    container_name: wimf-v2
    build:
      context: .
      target: production
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - net

  db:
    container_name: wimf-v2-db
    image: postgres
    env_file:
      - .env
    networks:
      - net
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./src/scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql

networks:
  net: